CREATE OR REPLACE TRIGGER DEBANK_RANKING_PROJECT_INSERT_INTO_ADDRESS_LIST_TRIGGER 
AFTER INSERT ON "DEBANK-USER-ASSET-PORTFOLIO-PROJECTS" 
	FOR EACH ROW
	EXECUTE
	    PROCEDURE DEBANK_RANKING_INSERT_INTO_ADDRESS_LIST_FUNC();
