version: '3.5'
networks:
  host:
    driver: host
services:
  redis:
    redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6371:6379
    command: redis-server --save 20 1 --loglevel warning

  api-wikiblock:
    image: registry.digitalocean.com/wikiblock/onchain-price:latest
    network_mode: host
    hostname: api.dev
    restart: always
    domainname: wikiblock.pro
    build: .
    volumes:
      - '.:/app'
    ports:
      - '9002:9002'
    depends_on:
      - redis
volumes:
  pgdata:
