// Generated by https://quicktype.io

import { Asset } from '../asset/asset.type';

export interface AssetTrending extends Asset {
  token_id: number;
  id_of_sources: {
    CoinGecko: string;
    CoinMarketCap: string;
  };
  order: number;
  name: string;
  rank: number;
  symbol: string;
  logo_url: string;
  official_web: string;
  platforms: {
    [key: string]: string;
  };
  present_on_chains: string[];
  predicted_date: number;
  market_cap: number;
  number_holders: number;
  trading_volume: number;
  price: number;
  price_change_percentage_24h: number;
  social_urls: {
    [key: string]: string & { twitter: string; facebook: string; reddit: string };
  };
  tags: string[];
  discovered_on: number;
  discovered_details: {
    price_discovered: number;
    trading_volume_discovered: number;
    market_cap_discovered: number;
    number_holders_discovered: number;
  };
}
