import { CountrySeed } from './country';
import { CategorySeed, mappingCategories } from './category';
import { PersonSeed, personInvestment, insertPersons } from './person';
import { ProductSeed, insertProducts } from './product';
import { CompanySeed, companyInvestment, insertCompanies } from './company';
import { CoinSeed, insertCoins, cryptorankCoinsSeed, mappingCoins } from './coin';
import { UserSeed } from './user';
import { FundSeed, fundInvestment, insertFunds, cryptorankFundsSeed } from './fund';
import { FundraisingRoundSeed, insertFundraisingRounds, crawlFundraisingRoundsFromCoinCarp } from './fundraising-round';
(async () => {
  (await import('../loaders/loggerLoader')).default();
  await (await import('../loaders/mongoDBLoader')).default();

  await mappingCategories();
  // await UserSeed();
  // await CountrySeed();
  // await CategorySeed();
  // await CompanySeed();
  // await CoinSeed();
  // await cryptorankCoinsSeed();
  // await ProductSeed();
  // await PersonSeed();
  // await FundSeed();
  // await cryptorankFundsSeed();
  // await companyInvestment();
  // await personInvestment();
  // await fundInvestment();
  // await FundraisingRoundSeed();
  // await insertCoins();
  // await insertFunds();
  // await insertPersons();
  // await insertCompanies();
  // await insertProducts();
  // await insertFundraisingRounds();
  // await mappingCoins();
  process.on('exit', () => {
    console.info('✅ Run seed data successfully');
  });
  process.exit(0);
})();
