version: '3'
services:
  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - ${DB_PORT}:27017
  # environment:
  # - MONGO_INITDB_DATABASE= "${DB_NAME}"
  # - MONGO_INITDB_ROOT_USERNAME= "${DB_USERNAME}"
  # - MONGO_INITDB_ROOT_PASSWORD= "${DB_PASSWORD}"
  # volumes:
  #   - ./db/mongo:/data/db
  # restart: always
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning
networks:
  es-net:
    driver: bridge
