version: "3"

services:
  postgres:
    image: bitnami/postgresql:14
    restart: always
    environment:
      POSTGRESQL_USERNAME: "${DB_USERNAME}"
      POSTGRESQL_PASSWORD: "${DB_PASSWORD}"
      POSTGRESQL_DATABASE: "${DB_NAME}"
      PGPASSWORD: "${DB_PASSWORD}"
    ports:
      - ${DB_PORT}:5432
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
