POST http://localhost:8084/content/v1/events
Content-Type: application/json

{
  "name": "fox_test",
  "introduction": "1fox_test",
  "startDate": "2022-08-05 06:39:48.079",
  "endDate": "2022-08-02 14:39:48.079",
  "location": "1fox_bulding",
  "phone": "123456789",
  "email": "1fox@global.com",
  "website": "www.1fox.com",
  "categories":[
    {"id":"e023fd64-d163-45c6-a740-26f62f0b2136"}
  ],
  "cryptoAssetTags":[
    {"id":"8b070ef6-63c8-434d-96e0-25bb54c49ea0"},
    {"id":"3bd12e3d-82ce-47da-96e9-f7fe88b621cd"}
  ]
}

#####################related####################################################
GET http://localhost:8084/content/v1/events/?name=2fox_test&related=true&page=1&perPage=3&category=e023fd64-d163-45c6-a740-26f62f0b2136&cryptoAssetTags=8b070ef6-63c8-434d-96e0-25bb54c49ea0&cryptoAssetTags=3bd12e3d-82ce-47da-96e9-f7fe88b621cd&sortBy=event.startDate&sortOrder=ASC
#####################related####################################################
GET http://localhost:8084/content/v1/events/?page=1&perPage=3&category=e023fd64-d163-45c6-a740-26f62f0b2136&cryptoAssetTags=a095cc1e-dbbf-477d-9e0f-fb08ab0c1dac&cryptoAssetTags=ad1bcc71-8fd8-488a-bd32-d916adc1c7ff
##############################################################################
GET http://localhost:8084/content/v1/events/?page=1&perPage=3&category=e023fd64-d163-45c6-a740-26f62f0b2136
##############################################################################
